package com.VYang.flightTrackerAPI.repository;

import java.util.Optional;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.VYang.flightTrackerAPI.domain.UserData;

public interface UserRepository extends MongoRepository<UserData, String> {
    Optional<UserData> findByUsername(String username); // Automatically generated by Spring Boot (findBy convention)
}
